# Support the author by using the funding links below
# Developed and maintained by Jonathan Dolinschi with the help of other contributors
# Buy Me a Coffee: https://buymeacoffee.com/jdolinschi

buy_me_a_coffee: jdolinschi

# Your support motivates me to keep making useful little things like this
